### ISSUE TITLE
Create a utility library.

### ISSUE THREAD

**Issue by IridescentRose** [CrossCraft/CrossFire#1]
# Utilities Module:
- [x] Documentation
- [x] Generic Types (u8, u16, u32, u64)
- [x] Generic Reader / Writer interface
	- [x] Buffered Reader/Writer
- [x] Logger
	- [x] File Interface Abstraction
	- [x] Log Levels (Debug, Info, Warning, Error)
	- [x] Log Formatting (Timestamp, Tags)
	- [x] Multi-threaded Logging Support
- [x] Custom Assert
	- [x] Assert / Panic Function Abstraction
	- [x] Optional Assert Message
- [x] Timer
	- [x] High-resolution Timer
	- [x] Frame Delta Time Calculation
	- [x] Elapsed Time Calculation
- [x] Generic Allocators
	- [x] Red-Black Tree Allocator (General Purpose)
	- [x] Debug Allocator Layer (Track Alloc & Free)
		- [x] Leak Detection
		- [x] Usage Reporting
		- [x] Initialization Patterns 
	- [x] Arena Allocator (Linear)
	- [x] C Allocator
	- [x] Stack Allocator
	- [x] Fixed Stack Allocator (128kb)
- [x] Smart Pointers
	- [x] Shared Pointer
	- [x] Unique Pointer
- [x] File Utilities
	- [x] File Read/Write Abstraction
	- [x] Path Manipulation and Navigation
	- [x] Directory implementation
- [x] Thread Utilities
	- [x] Thread Abstraction
	- [x] Thread Pooling & Tasks
	- [x] Synchronization Primitives (Mutex, Semaphore, etc.)
- [x] Data Structures
	- [x] Dynamic Array
	- [x] Singly Linked List
	- [x] Queue 
	- [x] Stack
- [x] Event System
	- [x] Event Dispatcher
	- [x] Custom Event Types Definition
	- [x] Event Listeners Registration

**Comment by IridescentRose** [comment]
File should implement Base + Extension

**Comment by IridescentRose** [comment]
Base + Extension model implemented
