### ISSUE TITLE
Core Module

### ISSUE THREAD

**Issue by IridescentRose** [CrossCraft/CrossFire#9]
# Core Module
- [ ] Application
	- [ ] Application State Class
	- [ ] Update, Fixed Update, Draw Events
	- [ ] Thread and Event Timing
	- [ ] Custom Main()
- [ ] Platform
	- [ ] Configuration Options (Graphics API Selection, Headless, Networking, etc.)
	- [ ] Abstraction Layer 
- [ ] Graphics
	- [ ] Platform Generic Surface (Window)
		- [ ] GLFW Windowing Support
	- [ ] Platform Generic Graphics API 
		- [ ] Backend Renderers
			- [ ] OpenGL 4.1
			- [ ] GL ES 3.2
			- [ ] Vulkan 1.0
			- [ ] DX 11
	- [ ] Graphics Primitives
		- [ ] Vertex
		- [ ] Mesh
		- [ ] Texture Loading
		- [ ] Model Loading
- [ ] Input
	- [ ] Keyboard And Mouse Input Handling
	- [ ] Gamepad Support

**Comment by IridescentRose** [comment]
Also add tracy support
